language: rust

rust:
  - stable

services:
  - docker

jobs:
  include:
    - stage: Deploy
      script: echo "deploying to Docker Hub..."
      deploy:
        provider: script
        script: bash deploy.sh
        on:
          branch: master
