language: rust

rust:
  - stable

env:
  global:
    - secure: OcbQWWY74oF1b2YCZyMLgxuDcPUM1r+U0gAd+MZT6JPAmMHjWP4B/CubZfJxzWl2+LXgC5CnkTPTuREyOtPSkkx9+8CezFr7EuwLY3qU4QzsCdFU3x7uWSg8qTUoylhYs2wH5iRa9pF7gVB3aOtV2AarRT5f4xtPOGJERAObi5VuwpTRn/znQUG4GBcrkoJH4oNJiw/BR97ni+ZlVs1vgRI2eIE8WGiZ+0ghCkNLurISfGNqBnu48qGSSbpvsqv456d+B2e7eQskaifys0C30l+EjDnLuigpZm6ho8T2VVXqazYYBMw2v0o7VDw8DdjwULA91YC7VsnFlTRRapOfTWd9/ll/ceke5ASKcFV4p7Wk+7Wy6Z60DG9GxRy54gR6pYPJ1hTyD4sAtvlCbIVCPhTs2Q5UOcIn/SvBHkALUg2LjFGZ5dRkVu4ls0A+3zHEp7MGuWERn1OCyoaHLCGU6gNfJJbZEMsme0Vw8enhqWOOz//ypYp94dye5HYVO2G+w27s9p1fTxSNzIZfMnx1bYQEbrZe42vwdtZtGvAEhlxo9P8JVQDljEGBdtSpx/Ov2n1YG8o+ADVgZRyfzx+/blFHqHWHRJFsfP6pF29jDNLiOK3mZpecC/Vu9qKQ4aKqFit1Xecwb+08C2qZmvxm1kK7t/EoEAnqN6JGoAoQqcU=
    - secure: HidpC9omD1fwA9WksKTrFdg+BtjTjazBjS8rKHN8OoA4XBscJqKwmxf+gCcl00BDFcJs2/i8wvIuSpOIyPjUkYTEal8oUjROiDQzzyRYRPsTelrkzaXn/QBWlQn/6zvD0iXoidm87KwXdUyJyJbHgFYEDzkD9zNxiwXepMfXyzaSsvEGoyi8/VNIy/pyastlye/0h+j5jWWrLCNriSDXNo/LNb9JCkwXwCCGkf5J/qvHhZho3O8KBlwn7aL7hvUnFgMAqhYn3yB3a6jlVW8130J0joqPh+Ai6rJWZWcpyoaNADPV0D5lRRaCgVW0230XS6efSNNMfjaV4IodFMVtX4Fis7k1Og+pAZV8moKHwnv0umVFwSzCWzGfzVhX/2hIgio+B5k0PifqDWIWYhEjm6ZKWgOy3Z4DshAfOvIh3xT/BAFCGEyXKOupO+P3K1bNoppM7Ng02kelwzz+a2540rryr+newgAWxMVk3Lg2/rJXvgyM1776OtBtxlTKt/dUjrTq5jKsMmYibcKuV229fpzwLkAqAgDo5gB64Cf/XCjH1GuUHfB7TJ1oLghqkdeMBYc4fV4XYt/nEFPUO6gABKA3d5Bae9I1q2R/zGzE9Fe67nU2lv2znt6T5DWuSlKfF+I0eaBrCeJLvcnX5X3VXDYVd52OCGaCQ6i4MfC2jd0=
    - secure: MyKnW1gIFKUzb77es18/nV9YxwHUra3D0zKiYw16XBlnKwctm+DCT0fByeev7wQpub7DekvYy1PHqXNVsT6HA38tkuDa+4ZiexEI+Y1sF7NyaP5X95JV0Q3ZmNeCgtSRkZnpVxkECjzVIeIwWPuQjKA2RGcq/gxpJc/ssytn97jgULQ98zKiQvixVrv0FhRyquWoO/acj3D3IgcnLoBB9dfVYxwA7L9lonR8b1ALnzJ0wXodIO/Jy5RL8Q2bTtCoOfXdVeh4u3m3dLjuWxZH9zm9RcH6L61aL5hpFSrOhK5+//Dap39AhI4Sd+SCfjee7PetGRxV3nEcSmCoZl7ZzEV5ZrROEZvkPD9H1d18vVzlGIk8UmwCko4o92XDlDdANmSHrqz865hkWAxNvD8ltd7uyfsKMqWYpFwamYuKJM1nOxq5fxEwMZIWJ8c4na5ss8XhMRkM/vGXq0l6D4peuWtkQl6OclKYP6CJdn26j0xc6xpGjleMZVuQsX20za3hyt9o1uFvCbZhTPhMgJYYMWyR4fN9yqxRHNm61fYw8xsxYlgr7jHXcgZllUA9qSEGZ8HUkSL6ZJpC9wFLCu0bQm1GdG/wlXS59++cbp7h10Y58nvRSWf2H10av4vJTOjhHkOIje42Vk8EltHj1wwBPt+9mGz9oP83LfWmHT24qUk=

services:
  - docker

jobs:
  include:
    - stage: Deploy
      script: echo "deploying to Docker Hub..."
      deploy:
        provider: script
        script: bash deploy.sh
        on:
          branch: master
