[workspace]
members = [
    "crates/smmdb",
    "crates/smmdb-auth",
    "crates/smmdb-common",
    "crates/smmdb-db"
]

[profile]
[profile.release]
lto = "fat"
codegen-units = 1

[profile.dev]
opt-level = 1
